# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeSACFriends' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeSACFriends
  
  pod 'SnapKit', '~> 5.0.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'DoubleSlider'  

end
